site_name: CosmoTransitions (modernized)
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to dark

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex.js


plugins:
  - search

nav:
  - Home: index.md
  - Roadmap & Flowchart: roadmap.md
  - Architecture: architecture.md
  - Modules:
    - Helper Functions:
        - Miscellaneous Functions: modules/helper_functions/Miscellaneous_functions.md
        - Numerical Integration Functions: modules/helper_functions/Numerical_integration.md
        - Numerical Derivatives Functions: modules/helper_functions/Numerical_derivatives.md
        - Interpolation Functions: modules/helper_functions/interpolation_functions.md
    - Finite Temperature:
        - Finete T Functions: modules/finiteT/finiteT.md
    - Tunneling (1D):
        - Tunneling Functions: modules/tunneling1D/tunneling1D.md
    - Transition Finder:
        - Transition Functions: modules/transitionFinder/transitionFinder.md
    - Generic Potential:
        - Potential Functions: modules/generic_potential/generic_potential.md
docs_dir: docs
