site_name: CosmoTransitions (modernized)
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
        - class: mermaid
  - pymdownx.tasklist

plugins:
  - search
  - mermaid2

#extra_javascript:
#  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
#  - js/mermaid-init.js

nav:
  - Home: index.md
  - Roadmap & Flowchart: roadmap.md
  - Architecture: architecture.md
  - Modules:
    - Helper Functions: modules/helper_functions.md
    - Finite Temperature: modules/finiteT.md
    - Tunneling (1D): modules/tunneling1D.md
    - Transition Finder: modules/transitionFinder.md
    - Generic Potential: modules/generic_potential.md
    - Multi-field Plotting: modules/multi_field_plotting.md
docs_dir: docs
