site_name: CosmoTransitions (modernized)
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to dark

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search

nav:
  - Home: index.md
  - Roadmap & Flowchart: roadmap.md
  - Architecture: architecture.md
  - Examples (Core modules):
      - Tunneling 1D full example: examples/example_tunneling1D.md
  - Modules:
    - Helper Functions:
        - Miscellaneous Functions: modules/helper_functions/Miscellaneous_functions.md
        - Numerical Integration Functions: modules/helper_functions/Numerical_integration.md
        - Numerical Derivatives Functions: modules/helper_functions/Numerical_derivatives.md
        - Interpolation Functions: modules/helper_functions/interpolation_functions.md
    - Finite Temperature (One loop corrections):
        - Exact Thermal Integrals: modules/finiteT/Exact_Thermal_Integrals.md
        - Spline Thermal Integrals: modules/finiteT/Spline_Thermal_Integrals.md
        - Approx Thermal Integrals: modules/finiteT/Approx_Thermal_Integrals.md
        - Short Hand for All Thermal Integrals: modules/finiteT/Short_Hand_Jb&Jf.md
    - Tunneling (1D):
        - Single Field functions: modules/tunneling1D/single_field.md
        - Tests of SF functions: modules/tunneling1D/tests_single_field.md
    - Transition Finder:
        - Transition Functions: modules/transitionFinder/transitionFinder.md
    - Generic Potential:
        - Potential Functions: modules/generic_potential/generic_potential.md
docs_dir: docs
