"""
plot_glauber_run_results.py
================================

Post-processing plots for the thesis Gláuber runs.

This file is meant to live in the same directory as
``thesis_eft68_gw_results_upp.py`` and the result folders

    02_Glauber_pure_benchmarks/
    03_Glauber_pure_C_scan/

It does not recompute phase transitions, bounces or spectra.  It only reads the
CSV/JSON files already generated by the production runs and builds the summary
figures used in the thesis.

Implemented plots
-----------------
Run 02:
    1. Six GW spectrum figures:
       - one figure for each Lambda and daisy choice;
       - three C curves per figure;
       - detector sensitivity curves included.

    2. Three relative-difference figures:
       - one figure for each Lambda;
       - curves show the relative daisy effect on the spectrum;
       - the code also prints and saves alpha, beta/H and supercooling changes.

Run 03:
    1. Fixed-Lambda plots of alpha(C)*1e6, beta/H(C) and (Tc-Tn)/Tc(C)
       for no-daisy.
    2. Fixed-Lambda plots of alpha(C)*1e6, beta/H(C) and (Tc-Tn)/Tc(C)
       for with-daisy.
    3. Fixed-Lambda plots of the relative daisy effect on all three
       observables.

Author workflow note
--------------------
The plotting code is intentionally independent from the simulation code: the
simulation creates the raw result folders; this file reads them and creates the
figures.  This makes the thesis post-processing reproducible and lightweight.
"""

from __future__ import annotations

import csv
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Paths and visual conventions
# -----------------------------------------------------------------------------

HERE = Path(__file__).resolve().parent
DEFAULT_RUN02_DIR = HERE / "02_Glauber_pure_benchmarks"
DEFAULT_RUN03_DIR = HERE / "03_Glauber_pure_C_scan"
DEFAULT_RUN04_DIR = HERE / "04_EFT68_pure_benchmarks"
DEFAULT_RUN05_DIR = HERE / "05_EFT68_pure_c6_scan"

# The same sensitivity-curve colors used in the thesis GW plots.
SENSITIVITY_COLORS = {
    "LISA": "#d62728",    # red
    "DECIGO": "#ff7f0e",  # orange
    "BBO": "#f2c300",     # yellow/gold
}

# Required color order inside each fixed-Lambda run_02 figure.
C_CURVE_COLORS = {
    "small": "#2ca02c",   # green
    "medium": "#1f77b4",  # blue
    "large": "#9467bd",   # purple
}

# Line styles used to distinguish Lambda values in run_03 summary plots.
LAMBDA_LINESTYLES = {
    1000.0: "-",
    2000.0: "--",
    4000.0: ":",
}

OBSERVABLE_COLORS = {
    "alpha": "#2ca02c",       # green
    "beta": "#d62728",        # red
    "supercooling": "black",  # black
    "relative": "#6a3d9a",     # purple
}


# -----------------------------------------------------------------------------
# Optional import of detector sensitivity curves
# -----------------------------------------------------------------------------


def _try_import_sensitivity_functions() -> tuple[Any | None, Any | None, Any | None]:
    """
    Import the sensitivity curves from the project package.

    The script is expected to run from docs/Thesis/Tests5.  If the package is
    not already importable, we add the repository ``src`` directory to sys.path.
    """

    try:
        from CosmoTransitions.gravitational_Waves import (  # type: ignore
            lisa_sensitivity_s_pis,
            decigo_sensitivity_s_pis,
            bbo_sensitivity_s_pis,
        )
        return lisa_sensitivity_s_pis, decigo_sensitivity_s_pis, bbo_sensitivity_s_pis
    except Exception:
        pass

    repo_root = HERE.parents[2] if len(HERE.parents) >= 3 else HERE
    src_dir = repo_root / "src"
    if src_dir.exists() and str(src_dir) not in sys.path:
        sys.path.insert(0, str(src_dir))

    try:
        from CosmoTransitions.gravitational_Waves import (  # type: ignore
            lisa_sensitivity_s_pis,
            decigo_sensitivity_s_pis,
            bbo_sensitivity_s_pis,
        )
        return lisa_sensitivity_s_pis, decigo_sensitivity_s_pis, bbo_sensitivity_s_pis
    except Exception as err:
        print(
            "[warning] Could not import detector sensitivity curves from "
            f"CosmoTransitions: {err}. Detector curves will be skipped."
        )
        return None, None, None


LISA_SENS, DECIGO_SENS, BBO_SENS = _try_import_sensitivity_functions()


# -----------------------------------------------------------------------------
# General helpers
# -----------------------------------------------------------------------------


def _safe_float(value: Any, default: float = np.nan) -> float:
    """Convert a value to float when possible."""

    if value is None:
        return default

    try:
        out = float(value)
    except (TypeError, ValueError):
        return default

    return out if np.isfinite(out) else default


def _format_float_for_label(value: float, digits: int = 4) -> str:
    """Compact float formatting for plot labels."""

    value = float(value)
    if np.isclose(value, round(value)):
        return str(int(round(value)))
    return f"{value:.{digits}g}"


def _parse_safe_float_from_path_token(token: str) -> float:
    """Parse path tokens such as '3p83' or '11p23' into floats."""

    return float(token.replace("p", ".").replace("m", "-"))


def _save_figure(fig: plt.Figure, output_dir: str | Path, basename: str) -> tuple[Path, Path]:
    """Save figure as PDF and PNG."""

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pdf_path = output_dir / f"{basename}.pdf"
    png_path = output_dir / f"{basename}.png"

    fig.savefig(pdf_path, bbox_inches="tight")
    fig.savefig(png_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    return pdf_path, png_path


def _read_flat_diagnostics_csv(path: str | Path) -> dict[str, Any]:
    """
    Read a thesis_diagnostics.csv file stored as quantity,value pairs.
    """

    path = Path(path)
    if not path.exists():
        return {}

    out: dict[str, Any] = {}
    with path.open("r", newline="", encoding="utf-8") as fobj:
        reader = csv.DictReader(fobj)
        for row in reader:
            key = row.get("quantity", "")
            value = row.get("value", "")
            if key:
                out[key] = value

    return out


def _first_finite_from_mapping(mapping: Mapping[str, Any], keys: Sequence[str]) -> float:
    """Return the first finite float from a list of candidate keys."""

    for key in keys:
        value = _safe_float(mapping.get(key, np.nan))
        if np.isfinite(value):
            return value
    return np.nan


def _relative_difference(new: np.ndarray, ref: np.ndarray) -> np.ndarray:
    """Compute (new-ref)/ref safely."""

    new = np.asarray(new, dtype=float)
    ref = np.asarray(ref, dtype=float)

    out = np.full_like(new, np.nan, dtype=float)
    mask = np.isfinite(new) & np.isfinite(ref) & (np.abs(ref) > 0.0)
    out[mask] = (new[mask] - ref[mask]) / ref[mask]
    return out


def _draw_detector_sensitivities(ax: plt.Axes, f_mHz: np.ndarray) -> None:
    """Draw LISA, DECIGO and BBO sensitivity curves if available."""

    if LISA_SENS is None or DECIGO_SENS is None or BBO_SENS is None:
        return

    curves = [
        ("LISA", LISA_SENS, SENSITIVITY_COLORS["LISA"]),
        ("DECIGO", DECIGO_SENS, SENSITIVITY_COLORS["DECIGO"]),
        ("BBO", BBO_SENS, SENSITIVITY_COLORS["BBO"]),
    ]

    for label, fn, color in curves:
        try:
            y = np.asarray(fn(f_mHz), dtype=float)
        except Exception as err:
            print(f"[warning] Could not evaluate {label} sensitivity: {err}")
            continue

        mask = np.isfinite(f_mHz) & np.isfinite(y) & (f_mHz > 0.0) & (y > 0.0)
        if np.any(mask):
            ax.loglog(
                f_mHz[mask],
                y[mask],
                color=color,
                lw=1.75,
                alpha=0.92,
                label=label,
            )


def _style_for_lambda(lambda_value: float) -> str:
    """Return a deterministic line style for a Lambda curve."""

    lambda_value = float(lambda_value)
    for key, style in LAMBDA_LINESTYLES.items():
        if np.isclose(lambda_value, key):
            return style
    return "-."

def _format_value_for_filename(value: float | int) -> str:
    """Format numbers safely for filenames."""

    value_float = float(value)

    if np.isclose(value_float, round(value_float)):
        text = str(int(round(value_float)))
    else:
        text = f"{value_float:.6g}"

    return text.replace("-", "m").replace(".", "p")


def _ordered_value_color_map(values: Sequence[float]) -> dict[float, str]:
    """
    Assign colors by value ordering.

    Small  -> green
    medium -> blue
    large  -> purple

    This is the same visual convention used for the three C curves in run_02.
    Here we reuse it for the three c6 curves at fixed c8.
    """

    clean_values = sorted({float(value) for value in values if np.isfinite(float(value))})

    if not clean_values:
        return {}

    if len(clean_values) == 1:
        return {clean_values[0]: C_CURVE_COLORS["medium"]}

    if len(clean_values) == 2:
        return {
            clean_values[0]: C_CURVE_COLORS["small"],
            clean_values[1]: C_CURVE_COLORS["large"],
        }

    color_map: dict[float, str] = {}

    for i, value in enumerate(clean_values):
        if i == 0:
            color_map[value] = C_CURVE_COLORS["small"]
        elif i == len(clean_values) - 1:
            color_map[value] = C_CURVE_COLORS["large"]
        else:
            color_map[value] = C_CURVE_COLORS["medium"]

    return color_map

# -----------------------------------------------------------------------------
# Run 02: data discovery
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class Run02Record:
    """One run_02 point."""

    root: Path
    include_daisy: bool
    Lambda: float
    C: float
    spectrum_path: Path
    diagnostics_path: Path | None
    diagnostics: dict[str, Any]

    @property
    def daisy_label(self) -> str:
        return "with_daisy" if self.include_daisy else "no_daisy"



def _parse_lambda_C_from_folder(folder: Path) -> tuple[float, float]:
    """Parse Lambda and C from a result-folder name."""

    name = folder.name
    match = re.search(r"Glauber_C(?P<C>[0-9pm]+)_Lambda(?P<L>[0-9pm]+)", name)
    if not match:
        return np.nan, np.nan

    C = _parse_safe_float_from_path_token(match.group("C"))
    Lambda = _parse_safe_float_from_path_token(match.group("L"))
    return Lambda, C


def discover_run02_records(run02_dir: str | Path = DEFAULT_RUN02_DIR) -> list[Run02Record]:
    """
    Find all run_02 folders that contain a GW spectrum table.
    """

    run02_dir = Path(run02_dir)
    records: list[Run02Record] = []

    for daisy_folder, include_daisy in [("no_daisy", False), ("with_daisy", True)]:
        parent = run02_dir / daisy_folder
        if not parent.exists():
            print(f"[warning] Missing run_02 folder: {parent}")
            continue

        for folder in sorted(parent.glob("results_*")):
            if not folder.is_dir():
                continue

            spectrum_path = folder / "G0_gw_spectrum.csv"
            if not spectrum_path.exists():
                print(f"[run_02] Skipping {folder.name}: missing G0_gw_spectrum.csv")
                continue

            diagnostics_path = folder / "thesis_diagnostics.csv"
            diagnostics = _read_flat_diagnostics_csv(diagnostics_path)

            Lambda = _first_finite_from_mapping(
                diagnostics,
                ["model_parameters.Lambda_glauber", "gw_thermodynamics.Lambda_glauber"],
            )
            C = _first_finite_from_mapping(
                diagnostics,
                ["model_parameters.C_glauber", "gw_thermodynamics.C_glauber"],
            )

            if not np.isfinite(Lambda) or not np.isfinite(C):
                Lambda_folder, C_folder = _parse_lambda_C_from_folder(folder)
                Lambda = Lambda if np.isfinite(Lambda) else Lambda_folder
                C = C if np.isfinite(C) else C_folder

            if not np.isfinite(Lambda) or not np.isfinite(C):
                print(f"[run_02] Skipping {folder.name}: could not infer Lambda/C")
                continue

            records.append(
                Run02Record(
                    root=folder,
                    include_daisy=include_daisy,
                    Lambda=float(Lambda),
                    C=float(C),
                    spectrum_path=spectrum_path,
                    diagnostics_path=diagnostics_path if diagnostics_path.exists() else None,
                    diagnostics=diagnostics,
                )
            )

    # If the same point was run more than once, the automatic folder name can
    # change because the field cutoff appears in the path.  For plotting we keep
    # only the most recent folder for each (daisy, Lambda, C) point.  This makes
    # the post-processing robust under repeated runs.
    latest: dict[tuple[bool, float, float], Run02Record] = {}
    for record in records:
        key = (
            bool(record.include_daisy),
            round(float(record.Lambda), 8),
            round(float(record.C), 8),
        )
        previous = latest.get(key)
        if previous is None or record.root.stat().st_mtime >= previous.root.stat().st_mtime:
            latest[key] = record

    return sorted(
        latest.values(),
        key=lambda item: (item.include_daisy, item.Lambda, item.C),
    )


def _C_color_map_for_records(records: Sequence[Run02Record]) -> dict[float, str]:
    """
    Assign colors by C ordering: small green, medium blue, large purple.
    """

    Cs = sorted({float(record.C) for record in records})
    if not Cs:
        return {}

    if len(Cs) == 1:
        return {Cs[0]: C_CURVE_COLORS["medium"]}

    if len(Cs) == 2:
        return {Cs[0]: C_CURVE_COLORS["small"], Cs[1]: C_CURVE_COLORS["large"]}

    # The thesis benchmark uses three C values.  If more exist, the extremes
    # keep the requested colors and the interior points use blue.
    color_map: dict[float, str] = {}
    for i, C in enumerate(Cs):
        if i == 0:
            color_map[C] = C_CURVE_COLORS["small"]
        elif i == len(Cs) - 1:
            color_map[C] = C_CURVE_COLORS["large"]
        else:
            color_map[C] = C_CURVE_COLORS["medium"]
    return color_map


def _load_spectrum(path: str | Path, spectrum_column: str = "omega_total_max_turb") -> tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Load frequency and selected GW spectrum column."""

    df = pd.read_csv(path)

    if "f_mHz" not in df.columns:
        raise ValueError(f"{path} does not contain an f_mHz column.")

    if spectrum_column not in df.columns:
        fallback = "omega_total" if "omega_total" in df.columns else None
        if fallback is None:
            raise ValueError(
                f"{path} does not contain {spectrum_column!r} or 'omega_total'."
            )
        spectrum_column = fallback

    f = np.asarray(df["f_mHz"], dtype=float)
    y = np.asarray(df[spectrum_column], dtype=float)
    return f, y, df


def _load_spectrum_epsilon_band(path: str | Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:
    """
    Load the two GW spectra used to represent the turbulence uncertainty band.

    Solid line: epsilon_turb = 0, read from ``omega_total_no_turb``.
    Dashed line: epsilon_turb = 1, read from ``omega_total_max_turb``.

    Older result folders may only contain ``omega_total``.  In that case the
    same curve is used for both entries, so the plotting code remains backward
    compatible.
    """

    df = pd.read_csv(path)

    if "f_mHz" not in df.columns:
        raise ValueError(f"{path} does not contain an f_mHz column.")

    f = np.asarray(df["f_mHz"], dtype=float)

    if "omega_total_no_turb" in df.columns:
        omega_eps0 = np.asarray(df["omega_total_no_turb"], dtype=float)
    elif "omega_total" in df.columns:
        omega_eps0 = np.asarray(df["omega_total"], dtype=float)
    else:
        raise ValueError(f"{path} does not contain omega_total_no_turb or omega_total.")

    if "omega_total_max_turb" in df.columns:
        omega_eps1 = np.asarray(df["omega_total_max_turb"], dtype=float)
    elif "omega_total" in df.columns:
        omega_eps1 = np.asarray(df["omega_total"], dtype=float)
    else:
        omega_eps1 = omega_eps0.copy()

    return f, omega_eps0, omega_eps1, df


# -----------------------------------------------------------------------------
# Run 02 plots
# -----------------------------------------------------------------------------


def plot_run02_fixed_lambda_spectra(
    *,
    run02_dir: str | Path = DEFAULT_RUN02_DIR,
    spectrum_column: str = "omega_total_max_turb",
    y_limits: tuple[float, float] = (1e-21, 1e-9),
    x_limits: tuple[float, float] = (1e-3, 1e5),
) -> list[Path]:
    """
    Build six fixed-Lambda spectrum plots for run_02.

    For each Lambda and daisy choice, the three C curves are shown together.
    Each C is represented by the same visual convention used in the thesis GW
    plots:

    - solid curve: epsilon_turb = 0;
    - dashed curve: epsilon_turb = 1;
    - filled band: 0 <= epsilon_turb <= 1.

    The ``spectrum_column`` argument is kept for backward compatibility with
    earlier calls, but the preferred run_02 visualization uses the full
    epsilon_turb band whenever the required columns are available.
    """

    _ = spectrum_column  # kept only for backward-compatible function calls.

    records = discover_run02_records(run02_dir)
    output_dir = Path(run02_dir)
    saved: list[Path] = []

    for include_daisy in [False, True]:
        subset_daisy = [record for record in records if record.include_daisy == include_daisy]
        daisy_name = "with daisy" if include_daisy else "no daisy"
        daisy_file = "with_daisy" if include_daisy else "no_daisy"

        for Lambda in sorted({record.Lambda for record in subset_daisy}):
            subset = [record for record in subset_daisy if np.isclose(record.Lambda, Lambda)]
            if not subset:
                continue

            color_map = _C_color_map_for_records(subset)

            fig, ax = plt.subplots(figsize=(8.2, 5.2))

            f_ref: np.ndarray | None = None
            band_label_used = False

            for record in sorted(subset, key=lambda item: item.C):
                f, omega_eps0, omega_eps1, _df = _load_spectrum_epsilon_band(record.spectrum_path)
                if f_ref is None:
                    f_ref = f

                color = color_map.get(record.C, C_CURVE_COLORS["medium"])

                mask0 = np.isfinite(f) & np.isfinite(omega_eps0) & (f > 0.0) & (omega_eps0 > 0.0)
                mask1 = np.isfinite(f) & np.isfinite(omega_eps1) & (f > 0.0) & (omega_eps1 > 0.0)
                mask_band = mask0 & mask1

                if not np.any(mask0) and not np.any(mask1):
                    print(f"[run_02] No positive spectrum for {record.root}")
                    continue

                if np.any(mask_band):
                    y_lo = np.minimum(omega_eps0[mask_band], omega_eps1[mask_band])
                    y_hi = np.maximum(omega_eps0[mask_band], omega_eps1[mask_band])
                    ax.fill_between(
                        f[mask_band],
                        y_lo,
                        y_hi,
                        color=color,
                        alpha=0.15,
                        linewidth=0.0,
                        label=(r"$0\leq\epsilon_{\rm turb}\leq1$" if not band_label_used else "_nolegend_"),
                    )
                    band_label_used = True

                if np.any(mask0):
                    ax.loglog(
                        f[mask0],
                        omega_eps0[mask0],
                        lw=2.45,
                        ls="-",
                        color=color,
                        label=rf"$C={record.C:.4g}$",
                    )

                if np.any(mask1):
                    ax.loglog(
                        f[mask1],
                        omega_eps1[mask1],
                        lw=2.15,
                        ls="--",
                        color=color,
                        label="_nolegend_",
                    )

            if f_ref is not None:
                _draw_detector_sensitivities(ax, f_ref)

            style_handles = [
                Line2D([0], [0], color="black", lw=2.2, ls="-", label=r"$\epsilon_{\rm turb}=0$"),
                Line2D([0], [0], color="black", lw=2.0, ls="--", label=r"$\epsilon_{\rm turb}=1$"),
            ]
            handles, labels = ax.get_legend_handles_labels()
            handles = handles + style_handles
            labels = labels + [handle.get_label() for handle in style_handles]

            ax.set_xlim(*x_limits)
            ax.set_ylim(*y_limits)
            ax.set_xlabel(r"$f$ [mHz]")
            ax.set_ylabel(r"$h^2\Omega_{\rm GW}(f)$")
            ax.set_title(rf"Run 02: $\Lambda={Lambda:.0f}$ GeV, {daisy_name}")
            ax.grid(True, which="both", alpha=0.25)
            ax.legend(handles, labels, loc="best", fontsize=8)
            fig.tight_layout()

            basename = f"run02_GW_spectra_Lambda{int(round(Lambda))}_{daisy_file}"
            pdf_path, png_path = _save_figure(fig, output_dir, basename)
            saved.extend([pdf_path, png_path])

            print(f"[run_02] Saved {pdf_path}")

    return saved


def _run02_record_lookup(records: Sequence[Run02Record]) -> dict[tuple[bool, float, float], Run02Record]:
    """Create a lookup keyed by (include_daisy, Lambda, rounded C)."""

    lookup: dict[tuple[bool, float, float], Run02Record] = {}
    for record in records:
        key = (record.include_daisy, round(record.Lambda, 8), round(record.C, 8))
        lookup[key] = record
    return lookup


def _run02_matched_pairs(records: Sequence[Run02Record]) -> list[tuple[Run02Record, Run02Record]]:
    """
    Pair no-daisy and with-daisy run_02 records at the same Lambda and C.
    """

    lookup = _run02_record_lookup(records)
    pairs: list[tuple[Run02Record, Run02Record]] = []

    no_daisy_keys = [key for key in lookup if key[0] is False]
    for _, Lambda_key, C_key in sorted(no_daisy_keys, key=lambda item: (item[1], item[2])):
        no_key = (False, Lambda_key, C_key)
        yes_key = (True, Lambda_key, C_key)
        if yes_key in lookup:
            pairs.append((lookup[no_key], lookup[yes_key]))
        else:
            print(f"[run_02] No with-daisy match for Lambda={Lambda_key}, C={C_key}")

    return pairs


def _diagnostic_observables(record: Run02Record) -> dict[str, float]:
    """Extract alpha, beta/H and supercooling from one run_02 record."""

    diag = record.diagnostics
    Tc = _first_finite_from_mapping(diag, ["key_temperatures.Tc", "transition_observables.Tc"])
    Tn = _first_finite_from_mapping(diag, ["key_temperatures.Tn", "transition_observables.Tn"])

    supercooling = _first_finite_from_mapping(
        diag,
        [
            "key_temperatures.Tc_minus_Tn_over_Tc",
            "transition_observables.supercooling_fraction",
            "transition_observables.Tc_minus_Tn_over_Tc",
        ],
    )
    if not np.isfinite(supercooling) and np.isfinite(Tc) and np.isfinite(Tn) and Tc > 0.0:
        supercooling = (Tc - Tn) / Tc

    return {
        "alpha": _first_finite_from_mapping(
            diag,
            ["gw_scales.gw_alpha", "gw_thermodynamics.alpha", "gw_thermodynamics.T_alpha"],
        ),
        "beta_over_H": _first_finite_from_mapping(
            diag,
            ["gw_scales.gw_beta_over_H", "gw_thermodynamics.beta_over_H"],
        ),
        "supercooling": supercooling,
    }


def plot_run02_daisy_relative_difference(
    *,
    run02_dir: str | Path = DEFAULT_RUN02_DIR,
    spectrum_column: str = "omega_total_max_turb",
    x_limits: tuple[float, float] = (1e-3, 1e5),
    y_limits: tuple[float, float] | None = None,
) -> tuple[list[Path], Path]:
    """
    Plot the relative daisy effect on the GW spectrum for run_02.

    The relative difference is

        (Omega_with_daisy - Omega_no_daisy) / Omega_no_daisy.

    The function also prints and saves the relative differences of alpha,
    beta/H and (Tc-Tn)/Tc.
    """

    records = discover_run02_records(run02_dir)
    pairs = _run02_matched_pairs(records)
    output_dir = Path(run02_dir)
    saved: list[Path] = []
    diagnostic_rows: list[dict[str, Any]] = []

    for Lambda in sorted({pair[0].Lambda for pair in pairs}):
        subset = [pair for pair in pairs if np.isclose(pair[0].Lambda, Lambda)]
        if not subset:
            continue

        color_map = _C_color_map_for_records([pair[0] for pair in subset])

        fig, ax = plt.subplots(figsize=(8.2, 4.8))

        for no_record, yes_record in sorted(subset, key=lambda pair: pair[0].C):
            f_no, y_no, _ = _load_spectrum(no_record.spectrum_path, spectrum_column=spectrum_column)
            f_yes, y_yes, _ = _load_spectrum(yes_record.spectrum_path, spectrum_column=spectrum_column)

            if f_no.shape != f_yes.shape or not np.allclose(f_no, f_yes, rtol=1e-8, atol=0.0):
                y_yes = np.interp(f_no, f_yes, y_yes, left=np.nan, right=np.nan)

            rel = _relative_difference(y_yes, y_no)
            mask = np.isfinite(f_no) & np.isfinite(rel) & (f_no > 0.0)
            if not np.any(mask):
                continue

            ax.semilogx(
                f_no[mask],
                rel[mask],
                lw=2.35,
                color=color_map.get(no_record.C, C_CURVE_COLORS["medium"]),
                label=rf"$C={no_record.C:.4g}$",
            )

            obs_no = _diagnostic_observables(no_record)
            obs_yes = _diagnostic_observables(yes_record)

            row: dict[str, Any] = {
                "Lambda_GeV": no_record.Lambda,
                "C": no_record.C,
                "spectrum_relative_min": float(np.nanmin(rel[mask])) if np.any(mask) else np.nan,
                "spectrum_relative_max": float(np.nanmax(rel[mask])) if np.any(mask) else np.nan,
            }

            for key in ["alpha", "beta_over_H", "supercooling"]:
                no_val = obs_no[key]
                yes_val = obs_yes[key]
                row[f"{key}_no_daisy"] = no_val
                row[f"{key}_with_daisy"] = yes_val
                row[f"{key}_relative_difference"] = (
                    (yes_val - no_val) / no_val
                    if np.isfinite(no_val) and np.isfinite(yes_val) and no_val != 0.0
                    else np.nan
                )

            diagnostic_rows.append(row)

        ax.axhline(0.0, color="black", lw=1.0, ls="--", alpha=0.7)
        ax.set_xlim(*x_limits)
        if y_limits is not None:
            ax.set_ylim(*y_limits)
        ax.set_xlabel(r"$f$ [mHz]")
        ax.set_ylabel(r"$(\Omega_{\rm daisy}-\Omega_{0})/\Omega_{0}$")
        ax.set_title(rf"Run 02: relative daisy effect, $\Lambda={Lambda:.0f}$ GeV")
        ax.grid(True, which="both", alpha=0.25)
        ax.legend(loc="best", fontsize=9)
        fig.tight_layout()

        basename = f"run02_relative_daisy_spectrum_Lambda{int(round(Lambda))}"
        pdf_path, png_path = _save_figure(fig, output_dir, basename)
        saved.extend([pdf_path, png_path])
        print(f"[run_02] Saved {pdf_path}")

    diagnostics_path = output_dir / "run02_daisy_relative_diagnostics.csv"
    if diagnostic_rows:
        df_diag = pd.DataFrame(diagnostic_rows).sort_values(["Lambda_GeV", "C"])
        df_diag.to_csv(diagnostics_path, index=False)

        print("\n" + "=" * 76)
        print("Run 02 – relative daisy diagnostics")
        print("=" * 76)
        for _, row in df_diag.iterrows():
            print(
                f"Lambda={row['Lambda_GeV']:.0f} GeV, C={row['C']:.5g} | "
                f"dalpha/alpha={row['alpha_relative_difference']:.6g}, "
                f"dbeta/beta={row['beta_over_H_relative_difference']:.6g}, "
                f"dsc/sc={row['supercooling_relative_difference']:.6g}"
            )
        print(f"Saved: {diagnostics_path}")
        print("=" * 76)
    else:
        print("[run_02] No diagnostic pairs found for daisy comparison.")

    return saved, diagnostics_path


# -----------------------------------------------------------------------------
# Run 03: summary-table loading and plotting
# -----------------------------------------------------------------------------


def load_run03_summary(run03_dir: str | Path = DEFAULT_RUN03_DIR) -> pd.DataFrame:
    """Load the run_03 master CSV."""

    run03_dir = Path(run03_dir)
    csv_path = run03_dir / "run03_glauber_C_scan_summary.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"Could not find run03 summary CSV: {csv_path}")

    df = pd.read_csv(csv_path)

    # Normalize booleans when read from CSV.
    if "include_daisy" in df.columns:
        if df["include_daisy"].dtype == object:
            df["include_daisy"] = df["include_daisy"].astype(str).str.lower().isin(["true", "1", "yes"])
        else:
            df["include_daisy"] = df["include_daisy"].astype(bool)

    numeric_columns = [
        "Lambda_GeV",
        "C",
        "Tn_GeV",
        "Tc_GeV",
        "Tc_minus_Tn_over_Tc",
        "alpha",
        "beta_over_H",
        "omega_total_peak",
        "f_total_peak_mHz",
    ]
    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def _valid_fopt_rows(df: pd.DataFrame) -> pd.DataFrame:
    """Keep rows with finite thermodynamic observables."""

    required = ["Lambda_GeV", "C"]
    for col in required:
        if col not in df.columns:
            raise ValueError(f"run03 summary is missing required column {col!r}")

    # Do not require status string because old scans may not use the same text.
    mask = np.isfinite(df["Lambda_GeV"]) & np.isfinite(df["C"])
    return df.loc[mask].copy()


def _relative_run03_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pair no-daisy and with-daisy rows and compute relative differences.
    """

    data = _valid_fopt_rows(df).copy()
    data["C_key"] = data["C"].round(8)
    data["Lambda_key"] = data["Lambda_GeV"].round(8)

    no = data[data["include_daisy"] == False].copy()
    yes = data[data["include_daisy"] == True].copy()

    merged = pd.merge(
        no,
        yes,
        on=["Lambda_key", "C_key"],
        suffixes=("_no", "_yes"),
        how="inner",
    )

    out = pd.DataFrame()
    if merged.empty:
        return out

    out["Lambda_GeV"] = merged["Lambda_GeV_no"]
    out["C"] = merged["C_no"]

    for col in ["alpha", "beta_over_H", "Tc_minus_Tn_over_Tc"]:
        no_col = f"{col}_no"
        yes_col = f"{col}_yes"
        out[f"{col}_no"] = merged[no_col]
        out[f"{col}_yes"] = merged[yes_col]

        numerator = merged[yes_col] - merged[no_col]
        denominator = merged[no_col]
        rel = np.full(len(merged), np.nan, dtype=float)
        mask = np.isfinite(numerator) & np.isfinite(denominator) & (np.abs(denominator) > 0.0)
        rel[mask] = numerator[mask] / denominator[mask]
        out[f"{col}_relative"] = rel

    return out


def _plot_run03_observables_one_lambda(
    df: pd.DataFrame,
    *,
    output_dir: str | Path,
    include_daisy: bool,
    Lambda: float,
) -> list[Path]:
    """
    Plot alpha(C), beta/H(C), and (Tc-Tn)/Tc(C) for one fixed Lambda.

    A fixed-Lambda plot is the correct representation here because every Lambda
    scan uses a different C interval.  The three observables have different
    units/scales, so we use three y-axes while keeping a common C axis.
    """

    output_dir = Path(output_dir)
    data = _valid_fopt_rows(df[df["include_daisy"] == include_daisy])
    data = data[np.isclose(data["Lambda_GeV"], float(Lambda))].sort_values("C")

    if data.empty:
        return []

    daisy_text = "with daisy" if include_daisy else "no daisy"
    daisy_file = "with_daisy" if include_daisy else "no_daisy"

    x = data["C"].to_numpy(dtype=float)
    alpha_scaled = 1.0e6 * data["alpha"].to_numpy(dtype=float)
    beta = data["beta_over_H"].to_numpy(dtype=float)
    supercooling = data["Tc_minus_Tn_over_Tc"].to_numpy(dtype=float)

    fig, ax_alpha = plt.subplots(figsize=(8.5, 5.2))
    ax_beta = ax_alpha.twinx()
    ax_super = ax_alpha.twinx()
    ax_super.spines["right"].set_position(("axes", 1.15))
    ax_super.spines["right"].set_visible(True)

    mask_alpha = np.isfinite(x) & np.isfinite(alpha_scaled)
    mask_beta = np.isfinite(x) & np.isfinite(beta)
    mask_super = np.isfinite(x) & np.isfinite(supercooling)

    if np.any(mask_alpha):
        ax_alpha.plot(
            x[mask_alpha],
            alpha_scaled[mask_alpha],
            lw=2.4,
            marker="o",
            ms=4.0,
            color=OBSERVABLE_COLORS["alpha"],
            label=r"$10^6\alpha$",
        )

    if np.any(mask_beta):
        ax_beta.plot(
            x[mask_beta],
            beta[mask_beta],
            lw=2.4,
            marker="s",
            ms=3.8,
            color=OBSERVABLE_COLORS["beta"],
            label=r"$\beta/H$",
        )

    if np.any(mask_super):
        ax_super.plot(
            x[mask_super],
            supercooling[mask_super],
            lw=2.4,
            marker="^",
            ms=4.0,
            color=OBSERVABLE_COLORS["supercooling"],
            label=r"$(T_c-T_n)/T_c$",
        )

    ax_alpha.set_xlabel(r"$C$")
    ax_alpha.set_ylabel(r"$10^6\alpha$", color=OBSERVABLE_COLORS["alpha"])
    ax_beta.set_ylabel(r"$\beta/H$", color=OBSERVABLE_COLORS["beta"])
    ax_super.set_ylabel(r"$(T_c-T_n)/T_c$", color=OBSERVABLE_COLORS["supercooling"])

    ax_alpha.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["alpha"])
    ax_beta.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["beta"])
    ax_super.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["supercooling"])

    ax_alpha.set_title(rf"Run 03: $\Lambda={Lambda:.0f}$ GeV, {daisy_text}")
    ax_alpha.grid(True, alpha=0.25)

    lines1, labels1 = ax_alpha.get_legend_handles_labels()
    lines2, labels2 = ax_beta.get_legend_handles_labels()
    lines3, labels3 = ax_super.get_legend_handles_labels()
    ax_alpha.legend(lines1 + lines2 + lines3, labels1 + labels2 + labels3, loc="best", fontsize=9)

    # Leave room for the third y-axis.
    fig.tight_layout(rect=(0.0, 0.0, 0.86, 1.0))

    basename = f"run03_observables_vs_C_Lambda{int(round(float(Lambda)))}_{daisy_file}"
    return list(_save_figure(fig, output_dir, basename))


def _plot_run03_observables_by_lambda(
    df: pd.DataFrame,
    *,
    output_dir: str | Path,
    include_daisy: bool,
) -> list[Path]:
    """Plot the three thermodynamic observables separately for each Lambda."""

    data = _valid_fopt_rows(df[df["include_daisy"] == include_daisy])
    saved: list[Path] = []

    for Lambda in sorted(data["Lambda_GeV"].dropna().unique()):
        saved.extend(
            _plot_run03_observables_one_lambda(
                data,
                output_dir=output_dir,
                include_daisy=include_daisy,
                Lambda=float(Lambda),
            )
        )

    return saved


def _plot_run03_relative_one_lambda(
    df: pd.DataFrame,
    *,
    output_dir: str | Path,
    Lambda: float,
) -> list[Path]:
    """Plot the relative daisy effect for alpha, beta/H and supercooling."""

    rel = _relative_run03_dataframe(df)
    rel = rel[np.isclose(rel["Lambda_GeV"], float(Lambda))].sort_values("C")

    if rel.empty:
        return []

    x = rel["C"].to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=(8.3, 5.0))

    curves = [
        ("alpha_relative", OBSERVABLE_COLORS["alpha"], "o", r"$\Delta\alpha/\alpha$"),
        ("beta_over_H_relative", OBSERVABLE_COLORS["beta"], "s", r"$\Delta(\beta/H)/(\beta/H)$"),
        (
            "Tc_minus_Tn_over_Tc_relative",
            OBSERVABLE_COLORS["supercooling"],
            "^",
            r"$\Delta[(T_c-T_n)/T_c]/[(T_c-T_n)/T_c]$",
        ),
    ]

    for column, color, marker, label in curves:
        y = rel[column].to_numpy(dtype=float)
        mask = np.isfinite(x) & np.isfinite(y)
        if not np.any(mask):
            continue

        ax.plot(
            x[mask],
            y[mask],
            lw=2.35,
            marker=marker,
            ms=4.0,
            color=color,
            label=label,
        )

    ax.axhline(0.0, color="black", ls="--", lw=1.0, alpha=0.7)
    ax.set_xlabel(r"$C$")
    ax.set_ylabel(r"relative daisy effect")
    ax.set_title(rf"Run 03: relative daisy effect, $\Lambda={Lambda:.0f}$ GeV")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best", fontsize=8)
    fig.tight_layout()

    basename = f"run03_relative_daisy_effect_Lambda{int(round(float(Lambda)))}"
    return list(_save_figure(fig, output_dir, basename))


def _plot_run03_relative_by_lambda(df: pd.DataFrame, *, output_dir: str | Path) -> list[Path]:
    """Plot the relative daisy effect separately for each Lambda."""

    rel = _relative_run03_dataframe(df)
    saved: list[Path] = []

    if rel.empty:
        return saved

    for Lambda in sorted(rel["Lambda_GeV"].dropna().unique()):
        saved.extend(_plot_run03_relative_one_lambda(df, output_dir=output_dir, Lambda=float(Lambda)))

    return saved


def plot_run03_scan_observables(*, run03_dir: str | Path = DEFAULT_RUN03_DIR) -> list[Path]:
    """Build all run_03 post-processing figures."""

    run03_dir = Path(run03_dir)
    df = load_run03_summary(run03_dir)
    saved: list[Path] = []

    # Fixed-Lambda figures.  This is essential because each Lambda scan uses a
    # different C interval, so a single common C axis would be misleading.
    saved.extend(_plot_run03_observables_by_lambda(df, output_dir=run03_dir, include_daisy=False))
    saved.extend(_plot_run03_observables_by_lambda(df, output_dir=run03_dir, include_daisy=True))
    saved.extend(_plot_run03_relative_by_lambda(df, output_dir=run03_dir))

    for path in saved:
        print(f"[run_03] Saved {path}")

    return saved

# -----------------------------------------------------------------------------
# Run 04: EFT68 benchmark spectra
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class Run04Record:
    """One run_04 pure EFT68 benchmark point."""

    root: Path
    c8: float
    c6: float
    spectrum_path: Path
    diagnostics_path: Path | None
    diagnostics: dict[str, Any]


def _parse_c6_c8_from_folder(folder: Path) -> tuple[float, float]:
    """Parse c6/f^2 and c8/f^4 from a result-folder name."""

    name = folder.name

    match = re.search(
        r"c6f2(?P<c6>[0-9pm]+)_c8f4(?P<c8>[0-9pm]+)",
        name,
    )

    if not match:
        return np.nan, np.nan

    c6 = _parse_safe_float_from_path_token(match.group("c6"))
    c8 = _parse_safe_float_from_path_token(match.group("c8"))

    return c6, c8


def discover_run04_records(run04_dir: str | Path = DEFAULT_RUN04_DIR) -> list[Run04Record]:
    """
    Find all run_04 folders that contain a GW spectrum table.

    Robustness:
    - first tries to read c6/c8 from thesis_diagnostics.csv;
    - if that fails, parses c6/c8 from the folder name;
    - if the same point was run more than once, keeps the newest folder.
    """

    run04_dir = Path(run04_dir)
    records: list[Run04Record] = []

    if not run04_dir.exists():
        print(f"[warning] Missing run_04 folder: {run04_dir}")
        return records

    for folder in sorted(run04_dir.rglob("results_*")):
        if not folder.is_dir():
            continue

        spectrum_path = folder / "G0_gw_spectrum.csv"
        if not spectrum_path.exists():
            print(f"[run_04] Skipping {folder.name}: missing G0_gw_spectrum.csv")
            continue

        diagnostics_path = folder / "thesis_diagnostics.csv"
        diagnostics = _read_flat_diagnostics_csv(diagnostics_path)

        c6 = _first_finite_from_mapping(
            diagnostics,
            [
                "model_parameters.c6_over_f2_TeV2",
                "scan_parameters.c6_over_f2_TeV2",
            ],
        )
        c8 = _first_finite_from_mapping(
            diagnostics,
            [
                "model_parameters.c8_over_f4_TeV4",
                "scan_parameters.c8_over_f4_TeV4",
            ],
        )

        if not np.isfinite(c6) or not np.isfinite(c8):
            c6_folder, c8_folder = _parse_c6_c8_from_folder(folder)
            c6 = c6 if np.isfinite(c6) else c6_folder
            c8 = c8 if np.isfinite(c8) else c8_folder

        if not np.isfinite(c6) or not np.isfinite(c8):
            print(f"[run_04] Skipping {folder.name}: could not infer c6/c8")
            continue

        records.append(
            Run04Record(
                root=folder,
                c8=float(c8),
                c6=float(c6),
                spectrum_path=spectrum_path,
                diagnostics_path=diagnostics_path if diagnostics_path.exists() else None,
                diagnostics=diagnostics,
            )
        )

    latest: dict[tuple[float, float], Run04Record] = {}

    for record in records:
        key = (
            round(float(record.c8), 8),
            round(float(record.c6), 8),
        )
        previous = latest.get(key)

        if previous is None or record.root.stat().st_mtime >= previous.root.stat().st_mtime:
            latest[key] = record

    return sorted(
        latest.values(),
        key=lambda item: (item.c8, item.c6),
    )


def plot_run04_fixed_c8_spectra(
    *,
    run04_dir: str | Path = DEFAULT_RUN04_DIR,
    y_limits: tuple[float, float] = (1e-21, 1e-9),
    x_limits: tuple[float, float] = (1e-3, 1e5),
) -> list[Path]:
    """
    Build fixed-c8 spectrum plots for run_04.

    For each fixed c8/f^4, the three c6/f^2 curves are shown together.

    Visual convention:
    - small c6  -> green;
    - medium c6 -> blue;
    - large c6  -> purple;
    - solid line: epsilon_turb = 0;
    - dashed line: epsilon_turb = 1;
    - shaded band: 0 <= epsilon_turb <= 1.
    """

    records = discover_run04_records(run04_dir)
    output_dir = Path(run04_dir)
    saved: list[Path] = []

    if not records:
        print("[run_04] No valid records found.")
        return saved

    for c8 in sorted({record.c8 for record in records}):
        subset = [record for record in records if np.isclose(record.c8, c8)]

        if not subset:
            continue

        color_map = _ordered_value_color_map([record.c6 for record in subset])

        fig, ax = plt.subplots(figsize=(8.2, 5.2))

        f_ref: np.ndarray | None = None
        band_label_used = False

        for record in sorted(subset, key=lambda item: item.c6):
            f, omega_eps0, omega_eps1, _df = _load_spectrum_epsilon_band(record.spectrum_path)

            if f_ref is None:
                f_ref = f

            color = color_map.get(record.c6, C_CURVE_COLORS["medium"])

            mask0 = np.isfinite(f) & np.isfinite(omega_eps0) & (f > 0.0) & (omega_eps0 > 0.0)
            mask1 = np.isfinite(f) & np.isfinite(omega_eps1) & (f > 0.0) & (omega_eps1 > 0.0)
            mask_band = mask0 & mask1

            if not np.any(mask0) and not np.any(mask1):
                print(f"[run_04] No positive spectrum for {record.root}")
                continue

            if np.any(mask_band):
                y_lo = np.minimum(omega_eps0[mask_band], omega_eps1[mask_band])
                y_hi = np.maximum(omega_eps0[mask_band], omega_eps1[mask_band])

                ax.fill_between(
                    f[mask_band],
                    y_lo,
                    y_hi,
                    color=color,
                    alpha=0.15,
                    linewidth=0.0,
                    label=(
                        r"$0\leq\epsilon_{\rm turb}\leq1$"
                        if not band_label_used
                        else "_nolegend_"
                    ),
                )
                band_label_used = True

            if np.any(mask0):
                ax.loglog(
                    f[mask0],
                    omega_eps0[mask0],
                    lw=2.45,
                    ls="-",
                    color=color,
                    label=rf"$c_6/f^2={record.c6:.4g}$",
                )

            if np.any(mask1):
                ax.loglog(
                    f[mask1],
                    omega_eps1[mask1],
                    lw=2.15,
                    ls="--",
                    color=color,
                    label="_nolegend_",
                )

        if f_ref is not None:
            _draw_detector_sensitivities(ax, f_ref)

        style_handles = [
            Line2D(
                [0],
                [0],
                color="black",
                lw=2.2,
                ls="-",
                label=r"$\epsilon_{\rm turb}=0$",
            ),
            Line2D(
                [0],
                [0],
                color="black",
                lw=2.0,
                ls="--",
                label=r"$\epsilon_{\rm turb}=1$",
            ),
        ]

        handles, labels = ax.get_legend_handles_labels()
        handles = handles + style_handles
        labels = labels + [handle.get_label() for handle in style_handles]

        ax.set_xlim(*x_limits)
        ax.set_ylim(*y_limits)
        ax.set_xlabel(r"$f$ [mHz]")
        ax.set_ylabel(r"$h^2\Omega_{\rm GW}(f)$")
        ax.set_title(rf"Run 04: $c_8/f^4={c8:.4g}$ TeV$^{{-4}}$")
        ax.grid(True, which="both", alpha=0.25)
        ax.legend(handles, labels, loc="best", fontsize=8)
        fig.tight_layout()

        basename = f"run04_GW_spectra_c8f4{_format_value_for_filename(c8)}"
        pdf_path, png_path = _save_figure(fig, output_dir, basename)
        saved.extend([pdf_path, png_path])

        print(f"[run_04] Saved {pdf_path}")

    return saved


# -----------------------------------------------------------------------------
# Run 05: EFT68 c6-scan loading and plotting
# -----------------------------------------------------------------------------


def load_run05_summary(run05_dir: str | Path = DEFAULT_RUN05_DIR) -> pd.DataFrame:
    """Load the run_05 master CSV."""

    run05_dir = Path(run05_dir)
    csv_path = run05_dir / "run05_eft68_c6_scan_summary.csv"

    if not csv_path.exists():
        raise FileNotFoundError(f"Could not find run05 summary CSV: {csv_path}")

    df = pd.read_csv(csv_path)

    if "include_daisy" in df.columns:
        if df["include_daisy"].dtype == object:
            df["include_daisy"] = (
                df["include_daisy"]
                .astype(str)
                .str.lower()
                .isin(["true", "1", "yes"])
            )
        else:
            df["include_daisy"] = df["include_daisy"].astype(bool)

    numeric_columns = [
        "c6_over_f2_TeV2",
        "c8_over_f4_TeV4",
        "f_GeV",
        "Tn_GeV",
        "Tc_GeV",
        "Tc_minus_Tn_over_Tc",
        "alpha",
        "beta_over_H",
        "omega_total_peak",
        "f_total_peak_mHz",
    ]

    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def _valid_eft68_rows(df: pd.DataFrame) -> pd.DataFrame:
    """Keep rows with finite c6 and c8."""

    required = ["c6_over_f2_TeV2", "c8_over_f4_TeV4"]

    for col in required:
        if col not in df.columns:
            raise ValueError(f"EFT68 summary is missing required column {col!r}")

    mask = (
        np.isfinite(df["c6_over_f2_TeV2"])
        & np.isfinite(df["c8_over_f4_TeV4"])
    )

    return df.loc[mask].copy()


def _plot_run05_observables_one_c8(
    df: pd.DataFrame,
    *,
    output_dir: str | Path,
    c8: float,
) -> list[Path]:
    """
    Plot alpha(c6), beta/H(c6), and (Tc-Tn)/Tc(c6) for one fixed c8.

    We use three y-axes because the three observables have very different
    numerical scales.
    """

    output_dir = Path(output_dir)
    data = _valid_eft68_rows(df)
    data = data[np.isclose(data["c8_over_f4_TeV4"], float(c8))].sort_values("c6_over_f2_TeV2")

    if data.empty:
        return []

    x = data["c6_over_f2_TeV2"].to_numpy(dtype=float)
    alpha_scaled = 1.0e6 * data["alpha"].to_numpy(dtype=float)
    beta = data["beta_over_H"].to_numpy(dtype=float)
    supercooling = data["Tc_minus_Tn_over_Tc"].to_numpy(dtype=float)

    fig, ax_alpha = plt.subplots(figsize=(8.5, 5.2))
    ax_beta = ax_alpha.twinx()
    ax_super = ax_alpha.twinx()

    ax_super.spines["right"].set_position(("axes", 1.15))
    ax_super.spines["right"].set_visible(True)

    mask_alpha = np.isfinite(x) & np.isfinite(alpha_scaled)
    mask_beta = np.isfinite(x) & np.isfinite(beta)
    mask_super = np.isfinite(x) & np.isfinite(supercooling)

    if np.any(mask_alpha):
        ax_alpha.plot(
            x[mask_alpha],
            alpha_scaled[mask_alpha],
            lw=2.4,
            marker="o",
            ms=4.0,
            color=OBSERVABLE_COLORS["alpha"],
            label=r"$10^6\alpha$",
        )

    if np.any(mask_beta):
        ax_beta.plot(
            x[mask_beta],
            beta[mask_beta],
            lw=2.4,
            marker="s",
            ms=3.8,
            color=OBSERVABLE_COLORS["beta"],
            label=r"$\beta/H$",
        )

    if np.any(mask_super):
        ax_super.plot(
            x[mask_super],
            supercooling[mask_super],
            lw=2.4,
            marker="^",
            ms=4.0,
            color=OBSERVABLE_COLORS["supercooling"],
            label=r"$(T_c-T_n)/T_c$",
        )

    ax_alpha.set_xlabel(r"$c_6/f^2$ [TeV$^{-2}$]")
    ax_alpha.set_ylabel(r"$10^6\alpha$", color=OBSERVABLE_COLORS["alpha"])
    ax_beta.set_ylabel(r"$\beta/H$", color=OBSERVABLE_COLORS["beta"])
    ax_super.set_ylabel(r"$(T_c-T_n)/T_c$", color=OBSERVABLE_COLORS["supercooling"])

    ax_alpha.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["alpha"])
    ax_beta.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["beta"])
    ax_super.tick_params(axis="y", labelcolor=OBSERVABLE_COLORS["supercooling"])

    ax_alpha.set_title(rf"Run 05: $c_8/f^4={c8:.4g}$ TeV$^{{-4}}$")
    ax_alpha.grid(True, alpha=0.25)

    lines1, labels1 = ax_alpha.get_legend_handles_labels()
    lines2, labels2 = ax_beta.get_legend_handles_labels()
    lines3, labels3 = ax_super.get_legend_handles_labels()

    ax_alpha.legend(
        lines1 + lines2 + lines3,
        labels1 + labels2 + labels3,
        loc="best",
        fontsize=9,
    )

    fig.tight_layout(rect=(0.0, 0.0, 0.86, 1.0))

    basename = f"run05_observables_vs_c6_c8f4{_format_value_for_filename(c8)}"
    return list(_save_figure(fig, output_dir, basename))


def plot_run05_scan_observables(*, run05_dir: str | Path = DEFAULT_RUN05_DIR) -> list[Path]:
    """Build all run_05 post-processing figures."""

    run05_dir = Path(run05_dir)
    df = load_run05_summary(run05_dir)

    saved: list[Path] = []
    data = _valid_eft68_rows(df)

    for c8 in sorted(data["c8_over_f4_TeV4"].dropna().unique()):
        saved.extend(
            _plot_run05_observables_one_c8(
                data,
                output_dir=run05_dir,
                c8=float(c8),
            )
        )

    for path in saved:
        print(f"[run_05] Saved {path}")

    return saved

# -----------------------------------------------------------------------------
# Main dispatcher
# -----------------------------------------------------------------------------


def run_all_postprocessing(
    *,
    run02_dir: str | Path = DEFAULT_RUN02_DIR,
    run03_dir: str | Path = DEFAULT_RUN03_DIR,
    run04_dir: str | Path = DEFAULT_RUN04_DIR,
    run05_dir: str | Path = DEFAULT_RUN05_DIR,
    run_run02: bool = True,
    run_run03: bool = True,
    run_run04: bool = True,
    run_run05: bool = True,
) -> dict[str, Any]:
    """Run all available post-processing plots."""

    outputs: dict[str, Any] = {}

    if run_run02:
        outputs["run02_spectra"] = plot_run02_fixed_lambda_spectra(run02_dir=run02_dir)
        outputs["run02_relative"] = plot_run02_daisy_relative_difference(run02_dir=run02_dir)

    if run_run03:
        outputs["run03_scan_observables"] = plot_run03_scan_observables(run03_dir=run03_dir)

    if run_run04:
        outputs["run04_spectra"] = plot_run04_fixed_c8_spectra(run04_dir=run04_dir)

    if run_run05:
        outputs["run05_scan_observables"] = plot_run05_scan_observables(run05_dir=run05_dir)

    return outputs


if __name__ == "__main__":
    run_all_postprocessing(
        run02_dir=DEFAULT_RUN02_DIR,
        run03_dir=DEFAULT_RUN03_DIR,
        run04_dir=DEFAULT_RUN04_DIR,
        run05_dir=DEFAULT_RUN05_DIR,
        run_run02=False,
        run_run03=False,
        run_run04=True,
        run_run05=True,
    )