name: Deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install "mkdocs-material>=9.5" "pymdown-extensions>=10.8"
      - run: mkdocs gh-deploy --force
      - run: mkdocs build --strict
